### PR TITLE
Added new prop: isGrowing

### PR DESCRIPTION
**Pull request by bonqus**
Hi, thank you for creating this package.
I had a use case where I needed the progress path to grow instead of shrink.
So I thought you might appreciate the contribution of an `isGrowing` prop.
In combination with `rotation` it solves my use case quite nicely. 

I'm not sure how you handle versioning, so I have kept that out of the pr.

### CODE REVIEW

**Comment by bonqus** [comment]
> Hey @bonqus, thanks for the PR :) It seems you were trying to achieve counting up? Is that correct? 

Not quite, it's still a countdown but the progress path just grows as the the duration time reaches the end, instead of shrinking untill it disappears.

**Comment by bonqus** [comment]
But this would also be nice in the context of counting up to some set duration.

**Comment by vydimitrov** [comment]
That's cool :) Can you add please some tests for this new feature and I can merge it? You can do something similar to what I have for the tests in the web and mobile packages.

**Comment by bonqus** [comment]
> That's cool :) Can you add please some tests for this new feature and I can merge it? You can do something similar to what I have for the tests in the web and mobile packages.

For sure, I will add it to the PR shortly :)

**Comment by Hedonismv** [comment]
> That's cool :) Can you add please some tests for this new feature and I can merge it? You can do something similar to what I have for the tests in the web and mobile packages.

Hey bro, are u here?

**Review by fablee1 — APPROVED** [review]

**Review by Hedonismv — APPROVED** [review]
lets do it

**Comment by bonqus** [comment]
> Hedonismv

Hi,
Yeah, sorry I've been and am currently unable to prioritize writing the test.

**Comment by vydimitrov** [comment]
Great, lets push it :)

**Comment by rgavinc** [comment]
This is great! Is it going to be merged?

**Comment by vydimitrov** [comment]
Hey @bonqus, [here](https://github.com/vydimitrov/react-countdown-circle-timer/commit/458b7a632af0c85256f04f690b269e8d9016e7df) is a commit with the tests for the `isGrowing` prop. Please either add them to your PR or I will create a new PR for this feature. It seems this is feature that people need, so lets get it out!

**Comment by bonqus** [comment]
> Hey @bonqus, [here](https://github.com/vydimitrov/react-countdown-circle-timer/commit/458b7a632af0c85256f04f690b269e8d9016e7df) is a commit with the tests for the `isGrowing` prop. Please either add them to your PR or I will create a new PR for this feature. It seems this is feature that people need, so lets get it out!

I've added the tests, thank you for writing them.

**Comment by vydimitrov** [comment]
Great job! Thanks for the PR. I am now merging this it.

**Pull request merged**
